### PR TITLE
 * initializing test client content_length to avoid compiler confusio…

### PR DESCRIPTION
**Pull request by icing**
…n, see #124.

### CODE REVIEW

**Review by bagder — APPROVED** [review]
:+1:

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Should we publish a new release for this?

**Comment by bagder** [comment]
I would at least appreciate a new tag to use so that my CI builds will go green again!

**Comment by tgeoghegan** [comment]
@bagder: I'm preparing release 0.7.1 in #126.

**Pull request merged**
