### PR TITLE
Initial take on configuring client authentication certificates

### PR DESCRIPTION
**Pull request by djc**
This pretty much adapts the server-side support to the client.

This is the Rust side of #123. @icing can you work with this?

### CODE REVIEW

**Comment by icing** [comment]
Looks good. Will start a branch to test it.👍🏻

**Comment by djc** [comment]
Feel free to just reuse this branch.

**Comment by icing** [comment]
Used this PR as patch against `main` and implemented machine certificate configuration in `mod_tls`,
so the server can authenticate against proxied backends via client certificates. 

Code and test cases in https://github.com/abetterinternet/mod_tls/tree/icing/machine-certs

Will merge this when rustls-ffi make a release with this feature. Many thanks!

**Review by icing — APPROVED** [review]
Works well in my mod_tls adaption and test suite.

**Pull request merged**
