### PR TITLE
Initial cargo-c conversion

### PR DESCRIPTION
**Pull request by lu-zero**
- [x] Remove the now-unneeded entries in Cargo.toml
- [x] Update the documentation 
- [ ] Port the tests to use `cargo ctest`

Addresses #11

### CODE REVIEW

**Comment by djc** [comment]
Would be nice to be a bit more explicit in your PR about the benefits: what does cargo-c provide over the previous setup?

**Comment by lu-zero** [comment]
The top 4 are:
- Correct shared library at least for *BSD, Linux, Windows and Mac platforms
- Pkgconfig files containing the correct link line for static linking.
- The ability to merge this crate back to the main rustls and use the normal crate to install the C-API without having to have Cargo.toml options that impact the normal crate usage, see how we do in rav1e and other projects.
- C-API tests integrated with the normal test harness using `cargo ctest` (yet to be done in this PR)

**Comment by lu-zero** [comment]
I can complete the set if there is consensus on using it.

**Comment by jsha** [comment]
I don't plan to integrate cargo-c right now, but thank you for showing how it could work.

**Comment by lu-zero** [comment]
Feel free to poke me when/if you'd like to add it and I'll freshen the patch. I can spin off the pkg-config generation code so you can use it for #220 in case it could help you.

**Pull request closed without merging**
