### PR TITLE
Update CHANGELOG for 0.10.0

### PR DESCRIPTION
**Pull request by jsha**
(belatedly)

### CODE REVIEW

**Review by cpu — APPROVED** [review]
LGTM. I looked through the diff and didn't spot any unaccounted for externally visible changes.

**Comment by cpu** [comment]
I think if this were rebased CI would pass and it could be merged.

**Comment by cpu** [comment]
@jsha @ctz I went ahead and rebased this on main. Could one of you +1 :pray:

**Review by ctz — APPROVED** [review]

**Comment by cpu** [comment]
Going to merge with the assumption that since Jsha wrote the changelog and it's unmodified he's an implicit +1 :laughing: 

Happy to tweak post-merge if need be.

**Comment by jsha** [comment]
Post-hoc this is great, thank you for rebasing and merging!

**Pull request merged**
