### PR TITLE
Shrink unsafe block

### PR DESCRIPTION
**Pull request by cactter**

### CODE REVIEW

**Comment by cpu** [comment]
@jsha Is there a reason you would prefer the `unsafe` blocks as-written, or should this be considered for rebasing + review?

**Comment by jsha** [comment]
This is suitable for rebasing + review!

**Comment by cpu** [comment]
> This is suitable for rebasing + review!

Sounds good. Rebased + fixed formatting errors.

**Review by ctz — APPROVED** [review]

**Comment by cpu** [comment]
Thanks @cactter !

**Pull request merged**
